services:
  - type: web
    name: bold_check
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      TELEGRAM_TOKEN: 8130372610:AAEpWlmaVAR7-5q42K6ED7NU0rBEuvDKeCYI
      TELEGRAM_CHAT_ID: "6094061742"
